# -*- coding: utf-8 -*-
"""ejercicio_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UCCq6ZP6LcQlo56Kzik6cFto--AayL9N
"""

#2) Escribir un programa que le pregunte al usuario una cantidad a invertir, el interés porcentual anual y el número de años,
# y muestre por pantalla el capital obtenido en la inversión redondeado a dos decimales.

inversion = float(input("Ingrese la cantidad a invertir: "))
interes = float(input("Ingrese el interes porcentual: "))
cantidad_años = float(input("Ingrese la cantidad de años: "))

#FORMULA
capital = inversion*((interes /100)+1)**cantidad_años
capital = round(capital,2)
print ("El capital final obtenido por la inversion es de:" + str(capital) )

