# -*- coding: utf-8 -*-
"""ejercicio_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HBZX3pBX1UnLLINqt7v3HCLo0Cv2-Cw-
"""

#3) Escribir un programa que haga transformaciones de pesos a dólares. Debe preguntarle al usuario si desea transformar de pesos mexicanos a dólares, de pesos chilenos a dólares, 
#o desde pesos argentinos a dólares. 
#Mostrar por pantalla la cantidad de monedas a convertir, la moneda que se convirtió y el monto en dólares.


print("Ingres 1 para cambiar pesos chilenos a dolar")
print("Ingres 2 para cambiar pesos mexicanos a dolar")
print("Ingres 3 para cambiar pesos argentinos a dolar")
moneda = int(input("Indique opcion a transformar: "))



if(moneda == 1):
  pesos = input(" La cantidad de pesos chilenos a transformar: ")
  if(int(pesos) > 0):
    transformacion =  int(pesos) / 850
    transformacion = round(transformacion, 2)
    print("La cantidad de pesos chilenos ingresados fue: " + pesos + " ,al hacer el cambio queda con un total de " + str(transformacion) + " dolar(es)")

elif(moneda == 2):
  pesos = input(" La cantidad de pesos mexicanos a transformar: ")
  if(int(pesos) > 0):
    transformacion = int(pesos) / 20
    transformacion = round(transformacion, 2)
    print("La cantidad de pesos mexicanos ingresados fue: " + pesos + " ,al hacer el cambio queda con un total de " + str(transformacion) + " dolar(es)")
  
elif(moneda == 3):
  pesos = input("La cantidad de pesos argentinos a transformar: ")
  if(int(pesos) > 0):
    transformacion = int(pesos) / 115
    transformacion = round(transformacion, 2)
    print("La cantidad de pesos argentinos ingresados fue: " + pesos + " ,al hacer el cambio queda con un total de " + str(transformacion) + " dolar(es)")
  

#tener en cuenta Peso Chileno a dólar: 855
                #Peso Mexicano a dólar: 20
                #Peso Argentino a dólar: 115